### ISSUE TITLE
Duplicate labels coming from the Texas map layer

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/TravelTime#112]
- [x] fix duplicate labels

- [x] Rename layer to "USGS Streamer" 

I'm not sure if this Texas layer is needed for the streams, but we should try to remove place names. With the default basemap, this causes duplicate place names

![image](https://user-images.githubusercontent.com/35497731/78608001-b8562d80-7825-11ea-8b0b-b81a1b838a82.png)
![image](https://user-images.githubusercontent.com/35497731/78607972-ad030200-7825-11ea-94f8-db4b3e462041.png)

**Comment by harper-wavra** [comment]
From Marty:
"It looks like this specific map layer has been tile cached, as in, its just images so you dont have the ability to toggle layers on off within it.  Looks like it was intended to be used over a basemap with no labels, so I think two options are (1) use it over a basemap with no labels or (2) find a different hydro basemap.   for (2) i think ESRI has one, and maybe national map does too"

I am not sure how we want to proceed with this issue, if anyone has any opinions please let me know.
