### ISSUE TITLE
"Stream flow gages were found" modal styling

### ISSUE THREAD

**Issue by mitchas** [USGS-WiM/TravelTime#138]
Adjust buttons to look better - full width centered text, maybe?

**Comment by kjacobsen16** [comment]
![image](https://user-images.githubusercontent.com/35497731/85586292-6c39ae80-b606-11ea-9b50-785bba821765.png)
A couple other fixes there:
- [x] Make the links* `<a>` tags so you can click them.

- [x] Flow value should say "N/A" and not have label if missing

(This might belong in a separate issue depending on how the popup is filled in)
