### ISSUE TITLE
First Catchment Display

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/TravelTime#143]
Need to improve our display and calculations of the intersection between raindrop and the stream network.

**Comment by HansVraga** [comment]
Image by Pete™
![image](https://user-images.githubusercontent.com/12058013/90789097-19aa0500-e2cc-11ea-8403-c75ae1ac2446.png)

**Comment by HansVraga** [comment]
Similar issue with upstream:
![image](https://user-images.githubusercontent.com/12058013/90789238-4bbb6700-e2cc-11ea-90b9-30c25bd1c9ca.png)

**Comment by HansVraga** [comment]
NLDI is working on adding endpoints to assist with this effort.

**Comment by tgross-usgs** [comment]
Find where the raindrop trace or clickpoint are in the first catchment.  

Find the length from the point to downstream end of segment. 

Use the VAA table to get slope and mean annual flow but don’t use VAA length 

Note: Dependency on NLDI services (see issues #160)
