### ISSUE TITLE
Fix map icon placement

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/TravelTime#144]
Map icon is getting centered on the click point, but the point of the icon should be pointing where the click point is
![MicrosoftTeams-image](https://user-images.githubusercontent.com/35497731/90789683-cc7a6300-e2cc-11ea-94db-eeb916f35e52.png)

**Comment by HansVraga** [comment]
Branch called marker placement, maybe not merged? 

@kjacobsen16  confirmed the MarkerPlacement branch fixed the issue, tagged Mitch in a pull request

**Comment by tgross-usgs** [comment]
Issue resolved with merge of MarkerPlacement branch
