### ISSUE TITLE
Downstream trace not working 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/TravelTime#148]
getting this on the test client multiple times
![image](https://user-images.githubusercontent.com/12058013/93239355-4674ff00-f748-11ea-903b-ccdcb9e04969.png)

**Comment by HansVraga** [comment]
Fair amount of troubleshooting going on around this. 
One avenue is to investigate this suggestion from NLDI team:
NOTE that you should switch over to the “navigation” end point… write up of changes here. https://webvadevvs04.er.usgs.gov/updates/nldi_update/

**Comment by tgross-usgs** [comment]
Duplicate of #165
