### ISSUE TITLE
Reports not populating with data

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/TravelTime#155]
The report tables and output options are not populating with data

![image](https://user-images.githubusercontent.com/16928289/103703583-063ec400-4f65-11eb-95a3-92b592552b03.png)

**Comment by tgross-usgs** [comment]
This issue is fixed with the pull request for branch TAG154_158_163
The table shown in the example above is a units table and has been removed with the addition of units to report table headers.
