### ISSUE TITLE
Check distance configuration and NLDI call

### ISSUE THREAD

**Issue by tgross-usgs** [USGS-WiM/TravelTime#165]
NLDI query is not working when a user changes the query from SI to Imperial units and changes the distance to 100 miles

**Comment by tim7en** [comment]
It was attaching a string instead of a number. Fixed.

**Comment by tim7en** [comment]
Ok, got it to work. The main reason why we had an issue was rounding, rounded down to 0 - service returns all the reaches.

**Comment by USGSPMM3** [comment]
This is still not working in the client as of 2/22

**Comment by tgross-usgs** [comment]
I believe Tim has this fixed on a branch that has not yet been merged. I labelled it as completed so we aren't duplicating efforts. @tim7en is this correct?
