### ISSUE TITLE
Charts are not displaying on test (footer and report)

### ISSUE THREAD

**Issue by tgross-usgs** [USGS-WiM/TravelTime#166]

**Comment by mitchas** [comment]
![totCharts](https://user-images.githubusercontent.com/4575782/106004240-a2498000-6078-11eb-995d-6a9c62ee9d97.PNG)

Related Error

**Comment by tim7en** [comment]
It is working inside of the dev branch ??! something is off with test side ? 
![Uploading image.png…]()

**Comment by kjacobsen16** [comment]
@tim7en I pulled down the dev branch last week and it was broken for me as well. I think if you run `npm install` it will break. I was able to fix it locally by adding the "ThemeService" to the providers in the app.module.ts.

I'm guessing there was an update to a package and it was triggered when the github action ran the build command (which also runs npm install)
