### ISSUE TITLE
Chart elements no longer displaying in report

### ISSUE THREAD

**Issue by tgross-usgs** [USGS-WiM/TravelTime#167]

**Comment by kjacobsen16** [comment]
The app.module.ts just needs to add "ThemeService" to the providers

**Comment by tim7en** [comment]
![image](https://user-images.githubusercontent.com/33203731/106627270-a1b45c00-6546-11eb-8e59-57ca53b819f7.png)
Chart elements displayed in report for dev branch. Probably something is off with test server-side.

**Comment by tim7en** [comment]
![image](https://user-images.githubusercontent.com/33203731/106627444-d3c5be00-6546-11eb-8d45-a064b3e21f6b.png)
Chart element is shown inside of report, probably bug with the test side.
