### ISSUE TITLE
Make connection to chart and map

### ISSUE THREAD

**Issue by tgross-usgs** [USGS-WiM/TravelTime#188]
Link up the chart curves so that when clicked, they highlight/zoom to the corresponding reach on the map.

**Comment by harper-wavra** [comment]
I am not sure where the chart curves are located in the app, could I get a little explanation/screen shot on where I can find them?

**Comment by tgross-usgs** [comment]
@harper-wavra the charts are located in the app-charts component. They can be viewed in both the footer and the report. I'm happy to hop on a call if it helps.

**Comment by harper-wavra** [comment]
I think I understand. So when users clicks on the points on the chart I circled in the image below, the map will highlight and zoom to the corresponding reach on the map like it does when you click on a row on the table to the left? If I am still understanding wrong then yes, we can hop on a quick call.
![image](https://user-images.githubusercontent.com/59063181/112152241-15baca00-8bb0-11eb-945c-24d183c1d8cb.png)

**Comment by tgross-usgs** [comment]
@harper-wavra that is exactly right. The table already has the functionality like you pointed out, we now need it implemented in the chart as well.
