### ISSUE TITLE
Rename Leftbar -> sidbar and populate it

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/TravelTime#22]
Notices that Sidebar (currently leftbar) was started, but not being used/implemented

- [x] Rename leftbar -> sidebar
- [ ] Move sidbar accordion component and associated methods etc to sidebar
- [x] remove leaflet search functionality and use USGS search 
- [x] add maplayers to sidebar

**Comment by jknewson** [comment]
timur adding maplayers and baselayers to sidebar

**Comment by tim7en** [comment]
duplicate issue, closed issue #23 awaiting review
