### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/TravelTime#23]
Lets try one of these leaflet components
[ngx-leaflet](https://github.com/Asymmetrik/ngx-leaflet)

It will set up some great interactions bindings that will help us interect across components
- [x] remove the leaflet legend
- [x] bind layers, basemaps, etc to a configurable environment file 
- [x] add stream layers (and USGS gage) layers

**Comment by tim7en** [comment]
awaiting review
