### ISSUE TITLE
Footer bar

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/TravelTime#24]
Create Footer bar, for results, See image 
![image](https://user-images.githubusercontent.com/8713714/63196587-d66ee380-c032-11e9-9ccc-95beadf9dae1.png)

Supplies user interaction with result table and flow lines and graphic to show plum migrating down stream

**Comment by jknewson** [comment]
initially hidden, then slides up when results are available

**Comment by tim7en** [comment]
![image](https://user-images.githubusercontent.com/33203731/73566661-66161c00-4432-11ea-8eb5-51d9cae7f2b2.png)
Added few more features. I feel this issue has multiple issues already inside.
