### ISSUE TITLE
Add Google Analytics 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/TravelTime#269]
We'll want to add the google tag info below to the index.html, and figure out what is important to document.

We can ask Pete what he might want to see, but initial thoughts are to track when equations are computed, when scenarios are added, edited or deleted, and any other basic function. We can include the region/state and statistic groups in case Pete wants to see the frequency of those things (or maybe say "all" if no filters are applied).

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-2C1QXBBXVH"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-2C1QXBBXVH');
</script>
```

**Comment by tgross-usgs** [comment]
@harper-wavra, @HansVraga... do you know where the id comes from (G-2C1QXBBXVH)? I assume its unique to each application?

**Comment by amedenblik** [comment]
Looks like Google Analytics is not enabled. ID is G-WYNJ98864G

![image](https://user-images.githubusercontent.com/40237491/161066302-bb05f727-67c6-4d26-975b-655e2fa5b61b.png)

**Comment by tgross-usgs** [comment]
I have a local branch where I began this work but it isn't finished. It's why we have the ID set up. The work has just been on hold.
