### ISSUE TITLE
Update NLDI service URL

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/TravelTime#293]
Users are reporting this error with the Time of Travel beta application:

![image](https://user-images.githubusercontent.com/40237491/153221885-09bedf03-7f62-4ba5-b0d0-ea49e7e26db2.png)

I assume this is happening because NLDI updated their service URL. See this issue for a similar fix: https://github.com/USGS-WiM/StreamStats-National/issues/138

**Comment by harper-wavra** [comment]
https://labs.waterdata.usgs.gov/api/nldi/pygeoapi/openapi?f=html#/nldi-flowtrace/executeNldi-flowtraceJob

**Comment by amedenblik** [comment]
Closed with #299
