### ISSUE TITLE
swap measurement labels

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/TravelTime#50]
Mixed up measurement labels - see image
![image](https://user-images.githubusercontent.com/12058013/70546914-af827300-1b35-11ea-968b-db19de847080.png)

**Comment by USGSPMM3** [comment]
Consider using "Spill Mass" and "Stream discharge" or "Streamflow"

**Comment by jknewson** [comment]
In addition Here are a few of my comments for the reach units (probably check w/ Pete to get his opinion) @USGSPMM3 

imperial/metric units for
Area -> sqr Miles/km
discharge -> CFS/CMS 
slope -> ft/ft / m/m
distance -> ft / m

**Comment by USGSPMM3** [comment]
I think for distance we can go to miles/kilometers. They will be small for individual reaches but I think for spill responses we'll be dealing with longer reaches.
