### ISSUE TITLE
Sort stream reaches before sending to jobsens

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/TravelTime#74]
We should sort the stream reaches by drainage area before passing it to jobsens to address out-of-order issues.

**Comment by tim7en** [comment]
So I reached out to Michael Weizcorek and he let me to use his tool to check for comid and geometry from nhdplus. 

![image](https://user-images.githubusercontent.com/33203731/73567064-85617900-4433-11ea-9514-bb865146427a.png)
Above you can see location on the map where reach appeared in the end of the downstream flow, however it is third by drainage area in the array of reaches. Notice location, shape and orientation.
Next I took that COMID 8421872 and check it with tool.
![image](https://user-images.githubusercontent.com/33203731/73567237-f143e180-4433-11ea-906d-b042ece74807.png)

Issue is related to the value of accumulated drainage area and returned basin properties for that COMID. It is related to NHDPLUS and I am not sure what else we can do here.

**Comment by tim7en** [comment]
Streams appear sorted before we send them to get time of travel. But, geometry returned or attributed basin drainage area incorrect.

**Comment by tgross-usgs** [comment]
Drainage area sort is in place prior to Jobson's service call. Discussed comparing sort order with fromNode and toNode (double check ID names with Pete) sort order. If they don't match we could alert user of bad data.

**Comment by USGSPMM3** [comment]
Are we sure we're getting total upstream drainage area? I was looking at the results when I click on a large river (i.e. Colorado River) vs. small tributary and the answers were relatively the same. In fact, it doesn't seem where I click, I'm getting almost identical answers close to 650 million (really need to resolve units issue to compare with real world numbers)

**Comment by USGSPMM3** [comment]
Realized a new issue (which I'll post). As the user selects different locations and plots "new" traces, the data in the footer table is not changing. When a new trace is created we need to erase the footer table data. This is part of the problem when looking at drainage area data (we're clicking multiple locations).
