### ISSUE TITLE
Table comments

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/TravelTime#77]
- Change Q to "Discharge" and include appropriate units
- Change Da to Drainage area and units should be changed to square kilometers or square miles and included in header.
- Compute cumulative length and push to table. Cumulative length can be called "Distance" or "Distance downstream from spill". Include appropriate units.
-V should be renamed to "Reach Velocity".
-Cup can be removed.
-Remove the individual reach times (Tl, Tp, and Td10). 
-Rename the Cumulative reach times (could get tricky, can we use a stacked header-see screen shot?).
-Is there anyway to "freeze" the column headers as you scroll down through the data in the footer?

![image](https://user-images.githubusercontent.com/16928289/73471102-1528f980-4346-11ea-8e99-fe1d1b7ae2b4.png)

**Comment by USGSPMM3** [comment]
I forgot, Ct should be "Concentration"  and units should probably be fixed to mg/L

**Comment by tim7en** [comment]
@tgross-usgs  I think you fixed these in the last update. Table headers looks like this 
![image](https://user-images.githubusercontent.com/33203731/73563507-75de3200-442b-11ea-8d26-2961f24110d6.png)

**Comment by tgross-usgs** [comment]
I spoke with Pete about this last week as he wasn't aware of the fact that you could hover on a header abbreviation and get the full name and units. We also decided that while the tables in the footer could have more abbreviations, that the report tables should have more details. Freezing table headers will be an easy fix.
