### ISSUE TITLE
Add qgage*qgage/qannual

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/TravelTime#8]
![image](https://user-images.githubusercontent.com/8713714/62476741-d59d9e00-b764-11e9-9af4-3473f9ab2ac8.png)

**Comment by jknewson** [comment]
This is something needed for a deliverable

**Comment by kjacobsen16** [comment]
I see the equation in the issue title is different than the equation in Pete's message. Just pointing that out so we make sure we use the right one.

**Comment by tim7en** [comment]
Since we don't have a gage flow value I assume relationship of Qgage/Qgage(annual) as 1. So the flow value kept as in the input.

**Comment by tim7en** [comment]
Qgage/Qgage(annual)*Q(i)

**Comment by USGSPMM3** [comment]
Clarification on the equation:
-Currently the user enters a discharge for the spill location "Qspill". 
-The Q annual of the spill location is retrieved from the flowline at the spill location "Qannual_spill". 
-Realtime streamflow values at downstream locations "QRT(i)" will be computed using the above two values and the mean value of the flowline "Qa(i)"

QRT(i)=Qa(i)*Qspill/Qannual_spill

This value can be computed for every downstream flowline for input into Jobson's equations.
